<a href="https://colab.research.google.com/github/hal-yu/datasci_1_loading/blob/main/HHA507W1_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Setting Up Google Colab.

# 2. Data Acquistion

1. Find and download at least 2-3 different CSV datasets (less than 10MB each) that do not contain any PHI/PII.
2. Similarly, find and download 3 XLSX files and 3 JSON files with the same criteria.
3. Use pandas to load each of these datasets into separate data frames in your Colab notebook.
4. Display the first 10 rows of each dataset in separate code cells.

In [10]:
import pandas as pd
import seaborn as sns
import plotly as plt

## 3 *CSV Datasets*

In [11]:
!pip freeze > packagestxt

### Top Rated Movies

#### Brief Description of Columns
*   'ID' is the ID number of the movie
*   'Genre ID' is the ID number of the genre
*   'Title' refers to the full title of the movie
*   'Overview' is the brief description of each movie
*   'Popularity' is the popularity rating of the movie
*   'Release Date' is the release date of the movie
*   'Vote_Average' is the avreage ratings out of 10
*   'Vote_Count' is the total number of vote counts

In [141]:
df1 = pd.read_csv('CSV_Datasets/MoviesTopRated.csv')
df1.head(10)

,Unnamed: 0,id,genre_ids,title,overview,popularity,release_date,vote_average,vote_count
0,0,238,"[18, 80]",The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",119.438,1972-03-14,8.7,18448
1,1,278,"[18, 80]",The Shawshank Redemption,Framed in the 1940s for the double murder of h...,90.415,1994-09-23,8.7,24376
2,2,240,"[18, 80]",The Godfather Part II,In the continuing saga of the Corleone crime f...,70.637,1974-12-20,8.6,11144
3,3,424,"[18, 36, 10752]",Schindler's List,The true story of how businessman Oskar Schind...,48.096,1993-12-15,8.6,14421
4,4,19404,"[35, 18, 10749]",Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",26.588,1995-10-20,8.6,4225
5,5,389,[18],12 Angry Men,The defense and the prosecution have rested an...,40.754,1957-04-10,8.5,7529
6,6,129,"[16, 10751, 14]",Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",73.067,2001-07-20,8.5,14730
7,7,372058,"[10749, 16, 18]",Your Name.,High schoolers Mitsuha and Taki are complete s...,66.572,2016-08-26,8.5,10152
8,8,496243,"[35, 53, 18]",Parasite,"All unemployed, Ki-taek's family takes peculia...",62.752,2019-05-30,8.5,16210
9,9,155,"[18, 28, 80, 53]",The Dark Knight,Batman raises the stakes in his war on crime. ...,83.163,2008-07-14,8.5,30333

### Crimes Data

#### Brief Description of Columns
*   'Year' is the year of crime from 2000-2019
*   'Population' is the number of people according to bureau of statistics
*   'Violent Crimes' is the number of violent crimes
*   'Violent Crime Rate' is the rate per 100000
*   'Murder Nonnegligent Manslaughter' is the number of murder cases per year
*   'Murder Nonngeligent Manslaughter Rate' is the rate of murder nonnegligent manslaughter
*   'Rape' is the number of rape cases
*   'Rape Rate' is the rate of the rape cases per 100000 persons
*   'Robbery' is the number of robbery cases
*   'Robbery rate' is the number of robbery cases per 100000 persons
*   'Aggravate assault' is the number of aggravated assault cases
*   'Aggravated assault rate' is the rate of aggravated assault per 100000 persons
*   'Property crime' is the numbers of property stolen crimes reported per year.
*   'Property crime rate is the rate of property theft per 100,000 persons
*   'Burglary' is the number burglary recorded per year
*   'Burglary rate' is the burglary rate per 100000 persons
*   'Burglary rate' is the burglary rate per 100000 persons
*   'Larceny-theft' is the numbers of larceny theft per year
*   'Larceny-theft rate' is the larceny theft rate per 100000 people
*   'Motor vehicle theft' is the numbers of motor stolen per year
*   'Motor vehicle theft rate' is the motor vehicle theft rate per 100000 persons

In [143]:
df2 = pd.read_csv('CSV_Datasets/crimes.dataset.csv')
df2.head(10)

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape\n(revised\ndefinition),Rape\n(revised\ndefinition)\nrate,Rape\n(legacy\ndefinition,Rape\n(legacy\ndefinition)\nrate,...,Aggravated\nassault,Aggravated\nassault rate,Property\ncrime,Property\ncrime\nrate,Burglary,Burglary\nrate,Larceny-\ntheft,Larceny-\ntheft rate,Motor\nvehicle\ntheft,Motor\nvehicle\ntheft\nrate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,...,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,...,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,...,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,...,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,...,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,...,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,...,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,...,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,...,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,...,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2

### Provisional Drug Overdose Death Counts

*   'Country' is the location being analyzed
*   'Vaccinated' is the vaccinated population
*   'FullyVaccinated' is the fully vaccinated population
*   'AdditionalDosagePer100 People' is the additional doses for every 100 people
*   'AdditionalDosageTotal' is the total amount of people that received additional dosages
*   'DosesAdministeredPer100People' is the amount of people that receieved vaccinations per 100 people
*   'DosesAdministeredTotal' is the total amount of people that received vaccination

In [144]:
df3 = pd.read_csv('CSV_Datasets/CovidVaccinations2023.csv')
df3.head(10)

,Country,Vaccinated,FullyVaccinated,AdditionalDosesPer100people,AdditionalDosesTotal,DosesAdministeredPer100people,DosesAdministeredTotal
0,World,72%,67%,35,2716491503,173.0,13270170332
1,Macau,>99%,>99%,76,477572,285.0,1797836
2,Brunei,>99%,>99%,78,340030,298.0,1289036
3,U.A.E.,>99%,>99%,53,5138699,255.0,24922054
4,Qatar,>99%,>99%,67,1903612,269.0,7606840
5,Samoa,97.00%,90.00%,42,82117,230.0,452831
6,Nepal,97%,85%,32,9025399,213.0,60976433
7,Chile,95.00%,93.00%,145,27474929,331.0,62688847
8,Malta,95%,94%,92,464470,275.0,1380226
9,Portugal,95.00%,87.00%,69,7043690,274.0,28106464

## *XLSX Files*

### Healthcare Diabetes Dataset

#### Brief Description of Columns

*   'ID' is the unique identifier
*   'Pregnancies' is the number of pregnancies of the ID
*   'Glucose' is the plasma glucose concentration from a 2-hour test
*   'BloodPressure' is the diastolic bloodpressure (mmHg)
*   'SkinThickness' is the triceps skinfold thickness(mm)
*   'Insulin' is the 2-hour serum insulin (muU/ml)
*   'BMI' is the body mass index (kg/m^2)
*   'DiabetesPedigreeFunction' is the diabetes pedigree function, a genetic score of diabetes
*   'Age' is the age in years
*   'Outcome; is the binary classification indicating the presence (1) or absence (0) of diabetes

In [138]:
df4 = pd.read_excel('XLSX_Datasets/diabetes.xlsx')
df4.head(10)

,Id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,6,148,72,35,0,33.6,0.627,50,1
1,2,1,85,66,29,0,26.6,0.351,31,0
2,3,8,183,64,0,0,23.3,0.672,32,1
3,4,1,89,66,23,94,28.1,0.167,21,0
4,5,0,137,40,35,168,43.1,2.288,33,1
5,6,5,116,74,0,0,25.6,0.201,30,0
6,7,3,78,50,32,88,31.0,0.248,26,1
7,8,10,115,0,0,0,35.3,0.134,29,0
8,9,2,197,70,45,543,30.5,0.158,53,1
9,10,8,125,96,0,0,0.0,0.232,54,1

### Drug Set

#### Brief Description of Columns
*   'Age' is the age of the patient
*   'Sex' is thegender of the patient
*   'BP' is the blood pressure levels
*   'Cholesterol' is the cholesterol levels
*   'Na_to_K' is the sodium to potassium ratio in blood
*   'Drug' is the drug type

In [137]:
df5 = pd.read_excel('XLSX_Datasets/drug.xlsx')
df5.head(10)

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY

### Valorant Esports

#### Brief Description of Columns


*   'Rank' is the place the teams rank by earnings
*   'Team; is the name of the team
*   'Gold' is the number of event where they ranked 1st
*   'Silver' is the number of events where the team finished 2nd
*   'Bronze' is the number of events where they finished 3rd
*   'S Tier' is the number of events where the team finished in 1st at a major event
*   'Earnings' is the total money won in valorant esports

In [135]:
df6 = pd.read_excel('XLSX_Datasets/val.xlsx')
df6.head(10)

   Rank             Team  Gold  Silver  Bronze  S Tier  Earnings
0     1        Sentinels    12       3       1       1    561500
1     2            Acend     5       1       1       1    498859
2     3   Gambit Esports     8       3       0       1    495638
3     4      Team Liquid     4       2       2       0    295374
4     5       G2 Esports     7       2       1       0    257925
5     6        Team Envy     2       2       2       0    251500
6     7      100 Thieves     2       3       2       0    225000
7     8  Vision Strikers    17       0       0       0    224149
8     9           Fnatic     1       2       2       0    210888
9    10      KRÜ Esports     7       3       1       0    191000

## *JSON Files*

In [80]:
import json

### Recipie Ingredients Dataset

#### Brief Description of Columns
*   'ID' is the recipie ID
*   'Cuisine' is the type of cuisine
*   'Ingredients' are the list of ingredients used in the recipie

In [145]:
df7 = pd.read_json('JSON_Datasets/Recipie.json', lines=False)
df7.head(10)

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...
5   6602     jamaican  [plain flour, sugar, butter, eggs, fresh ginge...
6  42779      spanish  [olive oil, salt, medium shrimp, pepper, garli...
7   3735      italian  [sugar, pistachio nuts, white almond bark, flo...
8  16903      mexican  [olive oil, purple onion, fresh pineapple, por...
9  12734      italian  [chopped tomatoes, fresh basil, garlic, extra-...

####

In [146]:
df8 = pd.read_json('JSON_Datasets/Countries.json')
df8.head(10)

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.0,9424702.9,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.0,9147420.0,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.0,1877519.0,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.0,770880.0,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
5,566,72951439.0,1.228520e+08,1.609529e+08,2.185412e+08,2.238046e+08,2.625804e+08,3.774599e+08,Nigeria,923768.0,910770.0,NG,NGA,0.1680,0.0241,0.0280,245.7312,636.4439,6
6,76,122288383.0,1.758737e+08,1.963535e+08,2.153135e+08,2.164224e+08,2.239090e+08,2.308857e+08,Brazil,8515767.0,8358140.0,BR,BRA,0.0393,0.0052,0.0270,25.8936,67.0645,7
7,50,83929765.0,1.291933e+08,1.483911e+08,1.711864e+08,1.729543e+08,1.844241e+08,2.039049e+08,Bangladesh,147570.0,130170.0,BD,BGD,0.0557,0.0103,0.0216,1328.6803,3441.2821,8
8,643,138257420.0,1.468448e+08,1.432426e+08,1.447133e+08,1.444444e+08,1.414327e+08,1.331330e+08,Russia,17098242.0,16376870.0,RU,RUS,-0.0158,-0.0019,0.0180,8.8200,22.8439,9
9,484,67705186.0,9.787344e+07,1.125324e+08,1.275041e+08,1.284556e+08,1.345341e+08,1.437724e+08,Mexico,1964375.0,1943950.0,MX,MEX,0.0299,0.0075,0.0160,66.0797,171.1463,10

In [147]:
df9 = pd.read_json('JSON_Datasets/Uni.json')
df9.head(10)

,rankingNoteText,nonResponderText,nonResponder,act-avg,primaryPhoto,primaryPhotoThumb,sat-avg,enrollment,city,sortName,...,displayName,schoolType,region,aliasNames,rankingType,overallRank,institutionalControl,rankingMaxPossibleScore,rankingRankStatus,primaryKey
0,NaN,None,False,32.0,https://www.usnews.com/img/college-photo_31291...,https://www.usnews.com/img/college-photo_31291...,1400.0,5400.0,Princeton,princetonuniversity,...,Princeton University,national-universities,NaN,None,national-universities,1,private,NaN,ranked,2627
1,NaN,None,False,32.0,https://www.usnews.com/img/college-photo_8866.jpg,https://www.usnews.com/img/college-photo_8866_...,1430.0,6710.0,Cambridge,harvarduniversity,...,Harvard University,national-universities,NaN,None,national-universities,2,private,NaN,ranked,2155
2,NaN,None,False,32.0,https://www.usnews.com/dims4/USNEWS/5b128f0/17...,https://www.usnews.com/dims4/USNEWS/196469f/17...,1450.0,5941.0,Chicago,universityofchicago,...,University of Chicago,national-universities,NaN,UChicago,national-universities,3,private,NaN,ranked,1774
3,NaN,None,False,32.0,https://www.usnews.com/dims4/USNEWS/60348dd/17...,https://www.usnews.com/dims4/USNEWS/1ca230f/17...,1420.0,5472.0,New Haven,yaleuniversity,...,Yale University,national-universities,NaN,None,national-universities,3,private,NaN,ranked,1426
4,NaN,None,False,32.0,https://www.usnews.com/img/college-photo_19002...,https://www.usnews.com/img/college-photo_19002...,1430.0,6113.0,New York,columbiauniversity,...,Columbia University,national-universities,NaN,None,national-universities,5,private,NaN,ranked,2707
5,NaN,None,False,33.0,https://www.usnews.com/img/college-photo_6935.jpg,https://www.usnews.com/img/college-photo_6935_...,1460.0,4524.0,Cambridge,massachusettsinstituteoftechnology,...,Massachusetts Institute of Technology,national-universities,NaN,MIT,national-universities,5,private,NaN,ranked,2178
6,NaN,None,False,31.0,https://www.usnews.com/img/college-photo_10369...,https://www.usnews.com/img/college-photo_10369...,1380.0,7034.0,Stanford,stanforduniversity,...,Stanford University,national-universities,NaN,None,national-universities,5,private,NaN,ranked,1305
7,NaN,None,False,32.0,https://www.usnews.com/img/college-photo_2743.jpg,https://www.usnews.com/img/college-photo_2743_...,1380.0,10019.0,Philadelphia,universityofpennsylvania,...,University of Pennsylvania,national-universities,NaN,UPenn,national-universities,8,private,NaN,ranked,3378
8,NaN,None,False,31.0,https://www.usnews.com/dims4/USNEWS/7e5b5e0/17...,https://www.usnews.com/dims4/USNEWS/3f12795/17...,1380.0,6609.0,Durham,dukeuniversity,...,Duke University,national-universities,NaN,None,national-universities,9,private,NaN,ranked,2920
9,NaN,None,False,34.0,https://www.usnews.com/img/college-photo_93.jpg,https://www.usnews.com/img/college-photo_93_17...,1510.0,979.0,Pasadena,californiainstituteoftechnology,...,California Institute of Technology,national-universities,NaN,CalTech Cal Tech,national-universities,10,private,NaN,ranked,1131

## Markdown Practice

1. Add a markdown cell and list the features (columns) of each dataset
2. For each feature, give a brief description of its content/purpose

## Submission

1. Within your repository, create a folder named "data" to store your acquired datasets.
2. Save your Colab notebook to your GitHub repository.
3. Submit the link to your GitHub repository.